[project]
name = 'Blockchain-Based-Legal-Compliance-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.audit-trail]
path = 'contracts/audit-trail.clar'
clarity_version = 2
epoch = 2.5

[contracts.documentation]
path = 'contracts/documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-verification]
path = 'contracts/entity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-verification_]
path = 'contracts/entity-verification_.clar'
clarity_version = 2
epoch = 2.5

[contracts.implementation]
path = 'contracts/implementation.clar'
clarity_version = 2
epoch = 2.5

[contracts.requirement-tracking]
path = 'contracts/requirement-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
